### ISSUE TITLE
How to bypass NotZeroFilled error

### ISSUE THREAD

**Issue by tteke** [gadomski/las-rs#32]
Probably this issue is not with this repo but the LAS spec itself but for the few pointclouds I have, las-rs panics with NotZeroFilled error. I can view them in any viewer and I can read them in liblas(cpp). Is it an error that can be just ignored or if not how can I fix these pointclouds ?

**Comment by gadomski** [comment]
There's a possibility this issue could be fixed by #31, and see #24 for a bit of background discussion on the topic of standard correctness vs Just Read The D*** File. Two questions:
- Does the problem exist in latest version (v0.7.2)?
- If so, can you provide more information on the field that's causing the error?

**Comment by tteke** [comment]
Latest version on the crates.io seems to be v0.7.1. I couldnt figure out which field, it just says bites are zero filled and prints out the bytes vec.

**Comment by gadomski** [comment]
I forgot to publish v0.7.2 (apparently). I just published, so `cargo update` and see if that fixes your problem.

**Comment by tteke** [comment]
Updating to 0.7.2 solved the issue, thanks.
