### ISSUE TITLE
Incorrect Start of First EVLR in Public Header Block

### ISSUE THREAD

**Issue by but0n** [gadomski/las-rs#84]
The calculation of point data length is only valid when exporting las file, i.e. without compression 
https://github.com/gadomski/las-rs/blob/34fd59653681a2c00ca337b400736d7a4478cd27/src/header/mod.rs#L708-L710
https://github.com/gadomski/las-rs/blob/34fd59653681a2c00ca337b400736d7a4478cd27/src/header/mod.rs#L679-L685

I also found a typo here:
https://github.com/gadomski/las-rs/blob/34fd59653681a2c00ca337b400736d7a4478cd27/src/raw/header.rs#L417-L419

**Comment by gadomski** [comment]
I _think_ that the calculation doesn't matter for compressed data, because we started ignore the `offset_to_point_data` in https://github.com/gadomski/las-rs/pull/76. Did you run into an error with reading or writing?

**Comment by but0n** [comment]
I'm using this library to generate COPC files. It is essentially a laz file with support of variable chunk size and two additional VLRs. However, it needs to know the offset to the first evlr. I found this error when using `start_of_first_evlr`. I think it would be handy to have a valid `start_of_first_evlr`.

**Comment by gadomski** [comment]
Right on, thanks @but0n. I believe the issue should be fixed by #91. I've done a large amount of refactoring as well, so the next release will be breaking. So you can test to make sure things are good (if you'd like), I'm going to release this as a beta version first (`v0.9.0-beta.0`) ... I'll update here when that's done.
